workflows:
  android-launcher:
    name: Android Launcher
    scripts:
      - name: Build APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
