workflows:
  android-launcher:
    name: Android Launcher
    scripts:
      - name: Build APK
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
