workflows:
  android-launcher:
    name: Android Launcher
    scripts:
      - name: Install Gradle
        script: |
          wget -q https://services.gradle.org/distributions/gradle-7.5-bin.zip
          unzip -q gradle-7.5-bin.zip
          export PATH=$PWD/gradle-7.5/bin:$PATH
      - name: Build APK
        script: |
          gradle assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
