workflows:
  android:
    name: Build Android APK
    max_build_duration: 30
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Set up Java
        script: |
          sudo update-java-alternatives --set java-1.17.0-openjdk-amd64
      - name: Clean project
        script: |
          ./gradlew clean
      - name: Build APK
        script: |
          ./gradlew assembleRelease --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - $CM_EMAIL
